# This file was generated by GoReleaser. DO NOT EDIT.
cask "ballast" do
  name "ballast"
  desc "CLI that installs AI agent rules for Cursor, Claude Code, OpenCode, and Codex"
  homepage "https://github.com/everydaydevopsio/ballast"
  version "5.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ballast"

  on_macos do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_amd64.tar.gz"
      sha256 "9c7db3f28669fc6362b9ae59a427a117a143c7080584e5933cac0c4c825f7faa"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_arm64.tar.gz"
      sha256 "5b538c65414972fc8052ca6eee503989df14b0c7a8bde6b3bdcf29c8a962a01c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_amd64.tar.gz"
      sha256 "0cb13627f5753c0af628376fe9c98c859f81e9496ebec254a981c7e5b2bbc85c"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_arm64.tar.gz"
      sha256 "ff1a34d6f483155aaffd2222bdc10157c092b7d4fbdd8e5ea38af702cbfaf0d1"
    end
  end

  # No zap stanza required
end
