# This file was generated by GoReleaser. DO NOT EDIT.
cask "ballast" do
  name "ballast"
  desc "CLI that installs AI agent rules for Cursor, Claude Code, OpenCode, and Codex"
  homepage "https://github.com/everydaydevopsio/ballast"
  version "4.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ballast"

  on_macos do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_amd64.tar.gz"
      sha256 "bdfaa871ceb927572d123712c13ed76ee578446126e0f1d77f3390223a44d702"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_arm64.tar.gz"
      sha256 "4ccfb39b2c9e2e64f76d89ba32375ad22b711fc6b017a2eea678fe4275248811"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_amd64.tar.gz"
      sha256 "e166635e172232eaf9cc463d8283f2de76a9c53892bf3ac7c85cd581d86880c2"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_arm64.tar.gz"
      sha256 "783b59a4211c61f5e9803fb37ced1d3420e590075396c3d30709e99f10662b02"
    end
  end

  # No zap stanza required
end
