# This file was generated by GoReleaser. DO NOT EDIT.
cask "ballast" do
  name "ballast"
  desc "CLI that installs AI agent rules for Cursor, Claude Code, OpenCode, and Codex"
  homepage "https://github.com/everydaydevopsio/ballast"
  version "5.18.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ballast"

  on_macos do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_amd64.tar.gz"
      sha256 "93803d0a33ab57f2f1a4e6258523168dd85b34776f2dfb172fc165850959fe9b"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_darwin_arm64.tar.gz"
      sha256 "6dbeb81dced0e171858d2377162d65ec743212f347f6a0db3c930cd7c4483289"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_amd64.tar.gz"
      sha256 "5c3436dda5a2544b1fdd078c33a07b411ee2b6791c3d6b5cfea3ca24187ffde2"
    end
    on_arm do
      url "https://github.com/everydaydevopsio/ballast/releases/download/v#{version}/ballast_#{version}_linux_arm64.tar.gz"
      sha256 "07f7e814d7fe5f2903530d3cb2481aaf7ae2e43c7db12ee95fb4fe3f438f721b"
    end
  end

  # No zap stanza required
end
