# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ballast < Formula
  desc "CLI that installs AI agent rules for Cursor, Claude Code, OpenCode, and Codex"
  homepage "https://github.com/everydaydevopsio/ballast"
  version "5.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.15.0/ballast_5.15.0_darwin_amd64.tar.gz"
      sha256 "27e9d04a633303608ec7a17417889532a706fd14c2e3e07ab5cddae307e33ca1"

      define_method(:install) do
        bin.install "ballast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.15.0/ballast_5.15.0_darwin_arm64.tar.gz"
      sha256 "38b8a265c38b266f2c1df1bf16f24058329404d5c8916bcd4596e18a6d99d3b3"

      define_method(:install) do
        bin.install "ballast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.15.0/ballast_5.15.0_linux_amd64.tar.gz"
      sha256 "0d4e8d74462f4f08f830965defa703837c54a4b010f41d31f8204e91be82ac24"
      define_method(:install) do
        bin.install "ballast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.15.0/ballast_5.15.0_linux_arm64.tar.gz"
      sha256 "7b162079ed4e277c4e0a740e3b2c6e9a0ea36ff8da0e4d302499f084a720f172"
      define_method(:install) do
        bin.install "ballast"
      end
    end
  end

  test do
    system "#{bin}/ballast", "--help"
  end
end
