# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ballast < Formula
  desc "CLI that installs AI agent rules for Cursor, Claude Code, OpenCode, and Codex"
  homepage "https://github.com/everydaydevopsio/ballast"
  version "5.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.11.1/ballast_5.11.1_darwin_amd64.tar.gz"
      sha256 "9924b841423b14dcafa083147ff6d5ce45b1d0d0884d4b90d29a36989d3a66d6"

      define_method(:install) do
        bin.install "ballast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.11.1/ballast_5.11.1_darwin_arm64.tar.gz"
      sha256 "1f29fc2ab9753e288fd1127c72e57e26744b2757fa730ed788c360a775d558ad"

      define_method(:install) do
        bin.install "ballast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.11.1/ballast_5.11.1_linux_amd64.tar.gz"
      sha256 "95c69a84ff93598c0545713c04410a09b49a26c33000a9a9fb72289d1792ceda"
      define_method(:install) do
        bin.install "ballast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everydaydevopsio/ballast/releases/download/v5.11.1/ballast_5.11.1_linux_arm64.tar.gz"
      sha256 "c9ad405baa6867cc6a210e11ce1e7f013cf0d78bc7d70e75c20e21672c9358ad"
      define_method(:install) do
        bin.install "ballast"
      end
    end
  end

  test do
    system "#{bin}/ballast", "--help"
  end
end
